language: c

install:
 - sudo apt-get update
 - sudo apt-get install cmake pkg-config liblua5.2-dev libpcap0.8-dev

before_script:
 - cmake .

script:
 - make

notifications:
  recipient:
   - alessandro@ghedini.me
  email:
    on_success: change
    on_failure: always
